JA2PYC/green_team_schedule

src/main/webapp/WEB-INF/views/ja2pyc_test.jsp

Ja2pyc front

---

src/main/webapp/WEB-INF/views/ja2pyc_test.jsp

Spring SSH

---

src/main/java/org/team/controller/HomeController.java
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

자바 패키지 이름 + 서블릿 base-package이름 =  org.team.schedule ->

---

src/main/webapp/WEB-INF/views/includes/footer.jsp
src/main/webapp/WEB-INF/views/includes/header.jsp
src/test/java/org/team/schedule/SampleTests.java

SampleTests

---

src/main/java/org/team/controller/HomeController.java
src/main/webapp/WEB-INF/spring/root-context.xml
src/test/java/org/team/controller/SampleTests.java
src/test/java/org/team/persistence/DataSourceTests.java

src/test/java 밑에 org.team.schedule 패키지 이름 = org.team.controller로 수정
DB연결 테스트 추가(hikari,mybatis)

HomeController = home 메소드 수정

---

src/main/java/org/team/controller/ReservationController.java

20241206 17:21

---

AS_Management.sql_Update_20241206.sql

성현님 registAS.jsp 파일에 따른 DB sql 자료 업뎃

DB업뎃20241206

---

src/main/java/org/team/controller/ScheduleController.java
src/main/webapp/WEB-INF/views/ja2pyc_test.jsp
src/main/webapp/resources/js/schedule/scheduleCalendar.js

Ja2pyc dto

---

src/main/java/org/team/controller/ScheduleController.java
src/main/webapp/WEB-INF/views/schedule/registAS.jsp
src/main/webapp/resources/js/schedule/scheduleCalendar.js

Merge branch 'master' of
https://github.com/JA2PYC/green_team_schedule.git into ja2pyc_front

Use Ny Mapper

---

src/main/resources/org/team/mapper/Ny_ReservationMapper.xml
src/main/webapp/WEB-INF/spring/root-context.xml

resources안에 org.team.mapper 수정

---

src/main/java/org/team/controller/ReservationController.java
src/main/webapp/WEB-INF/views/schedule/registAS.jsp

A/S접수하기 버튼 클릭시 오류 발생

---

src/main/webapp/WEB-INF/views/schedule/registAS.jsp

set visitdate

---

src/main/webapp/WEB-INF/views/New.jsp

모달창에 지도 표시 80%완료(문제 첫 로딩 시 제대로 표시안됨)

모달창에 지도 표시 80%완료(문제 첫 로딩 시 제대로 표시안됨)

---

src/main/java/org/team/controller/ScheduleController.java
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/includes/footer.jsp
src/main/webapp/WEB-INF/views/includes/headScript.jsp
src/main/webapp/WEB-INF/views/includes/header.jsp
src/main/webapp/WEB-INF/views/schedule/registResult.jsp
src/main/webapp/WEB-INF/views/schedule/scheduleCalendar.jsp
src/main/webapp/resources/css/base_style.css
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/home.css
src/main/webapp/resources/css/schedule/registAS.css
src/main/webapp/resources/css/schedule/registResult.css
src/main/webapp/resources/css/schedule/scheduleCalendar.css

set page style

---

ja2pyc_test_sql.sql
src/main/webapp/WEB-INF/spring/root-context.xml
src/main/webapp/WEB-INF/views/schedule/scheduleCalendar.jsp
src/main/webapp/resources/js/schedule/scheduleCalendar.js

set sms Service bean

---

src/main/webapp/WEB-INF/views/schedule/registAS.jsp
src/main/webapp/resources/css/schedule/scheduleCalendar.css
src/main/webapp/resources/js/schedule/scheduleCalendar.js

Ja2pyc testpc

---

src/main/webapp/WEB-INF/views/New.jsp

모달창 화면밖으로 나가는 현상 (거의)수정

---

src/main/java/org/team/controller/Ny_ReservationController.java
src/main/java/org/team/dto/BoardDTO.java
src/main/java/org/team/mapper/Ny_ReservationMapper.java
src/main/resources/org/team/mapper/Ny_ReservationMapper.xml
src/main/webapp/WEB-INF/views/read.jsp
src/main/webapp/WEB-INF/views/second_new.jsp

공지사항 게시판(페이징 기능) 기능만 추가

---

src/main/java/org/team/controller/Ny_ReservationController.java
src/main/java/org/team/dto/BoardDTO.java
src/main/java/org/team/mapper/Ny_ReservationMapper.java
src/main/resources/org/team/mapper/Ny_ReservationMapper.xml
src/main/webapp/WEB-INF/views/read.jsp
src/main/webapp/WEB-INF/views/second_new.jsp
src/test/java/org/team/mapper/ReservationMapperTests.java

공지사항 게시판 상세보기, 조회수 증가 완료

---

src/main/java/org/team/controller/BoardController.java
src/main/java/org/team/controller/ReservationController.java
src/main/java/org/team/controller/ScheduleController.java
src/main/java/org/team/mapper/BoardMapper.java
src/main/java/org/team/mapper/ScheduleMapper.java
src/main/resources/org/team/mapper/BoardMapper.xml
src/main/resources/org/team/mapper/ScheduleMapper.xml
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/post.jsp
src/main/webapp/WEB-INF/views/includes/headScript.jsp
src/main/webapp/WEB-INF/views/includes/header.jsp
src/main/webapp/resources/css/board/list.css
src/main/webapp/resources/css/board/post.css
src/main/webapp/resources/css/footer.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/privacyPolicy.css
src/main/webapp/resources/css/schedule/registAS.css
src/main/webapp/resources/css/terms.css

Schedule Mapper

---

src/main/webapp/WEB-INF/views/board/post.jsp
src/main/webapp/WEB-INF/views/home.jsp
src/main/webapp/WEB-INF/views/includes/header.jsp
src/main/webapp/WEB-INF/views/privacyPolicy.jsp
src/main/webapp/WEB-INF/views/schedule/processStatusBoard.jsp
src/main/webapp/WEB-INF/views/schedule/scheduleCalendar.jsp
src/main/webapp/WEB-INF/views/terms.jsp
src/main/webapp/resources/css/board/list.css
src/main/webapp/resources/css/board/post.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/home.css
src/main/webapp/resources/css/modal.css
src/main/webapp/resources/css/privacyPolicy.css
src/main/webapp/resources/css/schedule/processStatusBoard.css
src/main/webapp/resources/css/schedule/registAS.css
src/main/webapp/resources/css/schedule/scheduleCalendar.css
src/main/webapp/resources/css/terms.css
src/main/webapp/resources/js/modal.js
src/main/webapp/resources/js/schedule/scheduleCalendar.js

Set style css

---

src/main/webapp/WEB-INF/views/second_new.jsp

지도 경로 완성하기 과제(박성현)

---

src/main/java/org/team/controller/ReservationController.java
src/main/java/org/team/controller/ScheduleController.java
src/main/webapp/WEB-INF/views/schedule/registAS.jsp
src/main/webapp/WEB-INF/views/schedule/registResult.jsp
src/main/webapp/WEB-INF/views/schedule/scheduleCalendar.jsp
src/main/webapp/resources/css/base_style.css
src/main/webapp/resources/css/header.css
src/main/webapp/resources/css/modal.css
src/main/webapp/resources/css/schedule/registAS.css
src/main/webapp/resources/css/schedule/registResult.css
src/main/webapp/resources/js/modal.js
src/main/webapp/resources/js/schedule/registAS.js
src/main/webapp/resources/js/schedule/scheduleCalendar.js

Visittime Button

---

src/main/java/org/team/mapper/ScheduleMapper.java
src/main/java/org/team/service/ScheduleService.java
src/main/java/org/team/service/ScheduleServiceImpl.java
src/main/resources/org/team/mapper/ScheduleMapper.xml

Schedule Service

---

src/main/java/org/team/controller/Ny_ReservationController.java
src/main/webapp/WEB-INF/views/second_new.jsp

지도 출발지 목적지 경로 표시 완료(80%)

---

src/main/webapp/resources/js/kakaomap.js

map direction error

---

src/main/webapp/resources/js/kakaomap.js

map polyline

---

src/main/java/org/team/controller/BoardController.java
src/main/java/org/team/dto/BoardDTO.java
src/main/java/org/team/mapper/BoardMapper.java
src/main/resources/org/team/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/New.jsp
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/register.jsp

공지사항 글쓰기 기능 추가 완료(80%)

---

ja2pyc_test_sql.sql
src/main/webapp/WEB-INF/views/board/list.jsp
src/main/webapp/WEB-INF/views/board/register.jsp
src/main/webapp/resources/css/board/list.css
src/main/webapp/resources/css/board/register.css
src/main/webapp/resources/js/kakaomap.js

Board Register

---

src/main/java/org/team/controller/BoardController.java
src/main/java/org/team/mapper/BoardMapper.java
src/main/java/org/team/service/BoardService.java
src/main/java/org/team/service/BoardServiceImpl.java
src/main/resources/org/team/mapper/BoardMapper.xml
src/main/webapp/WEB-INF/views/board/post.jsp
src/main/webapp/WEB-INF/views/board/update.jsp

공지사항 수정하기, 삭제하기 기능 완료(80%)

---

src/main/webapp/WEB-INF/views/schedule/processStatusBoard.jsp
src/main/webapp/resources/css/schedule/processStatusBoard.css
src/main/webapp/resources/js/kakaomap.js
src/main/webapp/resources/js/schedule/processStatusBoard.js

process button

---

src/main/webapp/WEB-INF/views/board/post.jsp

remove replace
